# Generated by Django 3.2.9 on 2021-11-16 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_auto_20211116_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='storie',
            name='intro',
            field=models.CharField(default='a', max_length=200),
            preserve_default=False,
        ),
    ]
