# Generated by Django 3.2.9 on 2021-11-16 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_remove_storie_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='storie',
            name='intro',
            field=models.TextField(default='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec ligula blandit, egestas turpis nec, iaculis nunc. Vivamus at efficitur orci. Sed vitae pellentesque urna. Pellentesque feugiat eros.', max_length=200),
            preserve_default=False,
        ),
    ]
